name: Windows-RDP-VPS

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Cloudflared
      run: |
        curl -L --output cloudflared.exe https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password for runneradmin
      run: |
        $Password = ConvertTo-SecureString "MyPassword123" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password

    - name: Start Cloudflare Tunnel & Show URL
      run: |
        echo "Check the logs below for the '.trycloudflare.com' URL"
        ./cloudflared.exe tunnel --url tcp://localhost:3389
